# Generated by Django 4.0.3 on 2022-03-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
